services:
  web:
    build:
      dockerfile: Dockerfile
      secrets:
        - env
      args:
        REPO: https://github.com/formal-methods-mpi/MinervasArchive
        BRANCH: main
    env_file:
      - .env
secrets:
  env:
    file: ./.env
