services:
  web:
    build:
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - OPENAI_API_BASE=${OPENAI_API_BASE}
        - OPENAI_MODERATOR_NAME=${OPENAI_MODERATOR_NAME}
        - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
        - OPENAI_SUMMARIZER_NAME=${OPENAI_SUMMARIZER_NAME}
        - OPENAI_EMBEDDING_DEPLOYMENT_NAME=${OPENAI_EMBEDDING_DEPLOYMENT_NAME}
        - OPENAI_EMBEDDING_MODEL_NAME=${OPENAI_EMBEDDING_MODEL_NAME}
        - OPENAI_API_TYPE=${OPENAI_API_TYPE}
        - OPENAI_API_VERSION=${OPENAI_API_VERSION}
        - CHROMA_REPORT_DIR=${CHROMA_REPORT_DIR}
        - CHROMA_PERSON_DIR=${CHROMA_PERSON_DIR}
        - FAISS_REPORT_DIR=${FAISS_REPORT_DIR}
        - FAISS_PERSON_DIR=${FAISS_PERSON_DIR}
    environment:
      - OPENAI_API_KEY = ${OPENAI_API_KEY}
